var account = 
	{
	  "name": "Yatohime",
	  "battledeck": [
		0,2,3,4,5
	  ],
	  "cardscount" : 6,
	  "cards": {
		"0" :
		  {
			"id": 0,
			"name": "Lionny",
			"thumbnail": "http://vignette1.wikia.nocookie.net/valkyriecrusade/images/1/13/Lion_Dancer_G_icon.png",
			"image": "http://vignette2.wikia.nocookie.net/valkyriecrusade/images/1/1f/Lion_Dancer_H.png",
			"hp": 10000,
			"mana": 1,
			"attack": 2000,
			"defence": 10,
			"shield": 0,
			"element": "Light",
			"critical": 5,
			"multiplier": 2,
			"attack1": "Light Attack",
			"attack2": "Good Fortune",
			"s-attack": "Fireworks",
			"fireresist": 0.9,
			"waterresist": 0.9,
			"lightningresist": 0.9,
			"airresist": 0.9,
			"lightresist": 1,
			"darkresist": 2,
			"firebonus": 1,
			"waterbonus": 1,
			"lightningbonus": 1,
			"airbonus": 1,
			"lightbonus": 1.5,
			"darkbonus": 1
		  }, "1" :
		  {
			"id": 1,
			"name": "Monty",
			"thumbnail": "http://vignette1.wikia.nocookie.net/valkyriecrusade/images/8/89/Monster_Hunter_icon.jpg",
			"image": "http://vignette3.wikia.nocookie.net/valkyriecrusade/images/4/41/Monster_Hunter_H.png",
			"hp": 10000,
			"mana": 1,
			"attack": 2000,
			"defence": 10,
			"shield": 0,
			"element": "Fire",
			"critical": 5,
			"multiplier": 2,
			"attack1": "Fire Slash",
			"attack2": "Hunter Fest",
			"s-attack": "Raging Fire",
			"fireresist": 0.9,
			"waterresist": 0.9,
			"lightningresist": 0.9,
			"airresist": 0.9,
			"lightresist": 1,
			"darkresist": 2,
			"firebonus": 1,
			"waterbonus": 1,
			"lightningbonus": 1,
			"airbonus": 1,
			"lightbonus": 1.5,
			"darkbonus": 1
		  }, "2" :
		  {
			"id": 2,
			"name": "Fenrir",
			"thumbnail": "http://vignette1.wikia.nocookie.net/valkyriecrusade/images/d/d8/Ice_Wolf_Fenrir_G_icon.png",
			"image": "http://vignette1.wikia.nocookie.net/valkyriecrusade/images/2/29/Ice_Wolf_Fenrir_H.png",
			"hp": 10000,
			"mana": 1,
			"attack": 2000,
			"defence": 5,
			"shield": 0,
			"element": "Dark",
			"critical": 5,
			"multiplier": 2,
			"attack1": "Wolf Claw",
			"attack2": "Restrain",
			"s-attack": "Blizzard",
			"fireresist": 0.9,
			"waterresist": 0.9,
			"lightningresist": 0.9,
			"airresist": 0.9,
			"lightresist": 1,
			"darkresist": 2,
			"firebonus": 1,
			"waterbonus": 1,
			"lightningbonus": 1,
			"airbonus": 1,
			"lightbonus": 1.5,
			"darkbonus": 1
		  }, "3" :
		  {
			"id": 3,
			"name": "Zeus",
			"thumbnail": "http://vignette1.wikia.nocookie.net/valkyriecrusade/images/2/2f/Zeus_H_icon.png",
			"image": "http://vignette1.wikia.nocookie.net/valkyriecrusade/images/7/79/Zeus_H.png",
			"hp": 10000,
			"mana": 1,
			"attack": 2000,
			"defence": 5,
			"shield": 0,
			"element": "Lightning",
			"critical": 5,
			"multiplier": 2,
			"attack1": "Lightning",
			"attack2": "Thundershock",
			"s-attack": "Wrath of Thunder",
			"fireresist": 0.9,
			"waterresist": 0.9,
			"lightningresist": 0.9,
			"airresist": 0.9,
			"lightresist": 1,
			"darkresist": 2,
			"firebonus": 1,
			"waterbonus": 1,
			"lightningbonus": 1,
			"airbonus": 1,
			"lightbonus": 1.5,
			"darkbonus": 1
		  }, "4" : 
		  {
			"id": 4,
			"name": "Lugh",
			"thumbnail": "http://vignette3.wikia.nocookie.net/valkyriecrusade/images/b/b9/Lugh_H_icon.png",
			"image": "http://vignette2.wikia.nocookie.net/valkyriecrusade/images/9/94/Lugh_H.png",
			"hp": 10000,
			"mana": 1,
			"attack": 2000,
			"defence": 5,
			"shield": 0,
			"element": "Air",
			"critical": 5,
			"multiplier": 2,
			"attack1": "Wind Attack",
			"attack2": "Ring View",
			"s-attack": "Catasthrope",
			"fireresist": 0.9,
			"waterresist": 0.9,
			"lightningresist": 0.9,
			"airresist": 0.9,
			"lightresist": 1,
			"darkresist": 2,
			"firebonus": 1,
			"waterbonus": 1,
			"lightningbonus": 1,
			"airbonus": 1,
			"lightbonus": 1.5,
			"darkbonus": 1
		  }, "5" : 
		  {
			"id": 5,
			"name": "Icecle",
			"thumbnail": "http://vignette3.wikia.nocookie.net/valkyriecrusade/images/0/02/Icicle_G_icon.png",
			"image": "http://vignette1.wikia.nocookie.net/valkyriecrusade/images/6/67/Icicle_H.png",
			"hp": 10000,
			"mana": 1,
			"attack": 2000,
			"defence": 5,
			"shield": 0,
			"element": "Water",
			"critical": 5,
			"multiplier": 2,
			"attack1": "Ice Attack",
			"attack2": "Snow Strom",
			"s-attack": "Frozen Field",
			"fireresist": 0.9,
			"waterresist": 0.9,
			"lightningresist": 0.9,
			"airresist": 0.9,
			"lightresist": 1,
			"darkresist": 2,
			"firebonus": 1,
			"waterbonus": 1,
			"lightningbonus": 1,
			"airbonus": 1,
			"lightbonus": 1.5,
			"darkbonus": 1
		  } 
	  }
	}
	
var enemy = {
	"id": 666,
	"name": "Chaos",
	"thumbnail": "http://vignette3.wikia.nocookie.net/valkyriecrusade/images/c/ca/Chaos_H_icon.png",
	"image": "http://vignette2.wikia.nocookie.net/valkyriecrusade/images/2/2d/Chaos_H.png",
	"hp": 100000,
	"attack": 2000,
	"defence": 5,
	"shield": 0,
	"element": "Dark",
	"critical": 5,
	"multiplier": 2,
	"fireresist": 0.9,
	"waterresist": 0.9,
	"lightningresist": 0.9,
	"airresist": 0.9,
	"lightresist": 2,
	"darkresist": 1,
	"firebonus": 1,
	"waterbonus": 1,
	"lightningbonus": 1,
	"airbonus": 1,
	"lightbonus": 1.5,
	"darkbonus": 1
}

var skillList = {
	"cards": 
		  {
			"id": 0,
			"name": "Lionny",
			"thumbnail": "http://vignette1.wikia.nocookie.net/valkyriecrusade/images/1/13/Lion_Dancer_G_icon.png",
			"image": "http://vignette2.wikia.nocookie.net/valkyriecrusade/images/1/1f/Lion_Dancer_H.png",
			"hp": 10000,
			"attack": 2000,
			"defence": 10,
			"shield": 0,
			"element": "Light",
			"critical": 5,
			"multiplier": 2,
			"attack1": "Light Attack",
			"attack2": "Good Fortune",
			"s-attack": "Fireworks",
			"fireresist": 0.9,
			"waterresist": 0.9,
			"lightningresist": 0.9,
			"airresist": 0.9,
			"lightresist": 1,
			"darkresist": 2,
			"firebonus": 1,
			"waterbonus": 1,
			"lightningbonus": 1,
			"airbonus": 1,
			"lightbonus": 1.5,
			"darkbonus": 1
		  }
}

var BattleTurn = 1;
var playerActions = 0;



